bookapp/urls.py
from django.urls import path
from . import views
from .forms import AdminProfileUpdateView

from .forms import UsersListView, UserCreateView, UserEditView, UserDeleteView


urlpatterns = [
    path('home', views.home, name= 'home'),
    path('all_books', views.all_books, name = 'all_books'),
    path('category/<str:slug>', views.category_detail, name='category_detail'),
    path('<str:slug>', views.book_detail, name='book_detail'),
    path('searched_books/', views.search_book, name = 'book_search'),
    
    path('register/', views.register_page, name = 'register'),
    path('login/', views.login_page, name = 'login'),
    path('logout/', views.logout_user, name = 'logout'),
    
    path('borrow/<slug:slug>/', views.borrow_book, name='borrow_book'),
    path('my_borrowed_books/', views.my_borrowed_books, name='my_borrowed_books'),
    
    path('return_book/<int:pk>/', views.return_book, name='return_book'),
    
    
    
    path('builtadmin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('builtadmin/profile/', AdminProfileUpdateView.as_view(), name='admin_profile'),
    
    path('builtadmin/add_book/', views.add_book, name='add_book'),
    
    path('builtadmin/admin_all_books/', views.admin_all_books, name='admin_all_books'),
    path('builtadmin/edit_book/<int:pk>/', views.edit_book, name='edit_book'),
    path('builtadmin/delete_book/<int:pk>/', views.delete_book, name='delete_book'),
    path('builtadmin/admin_search_books/', views.admin_search_books, name='admin_search_books'),
    path('builtadmin/users/', UsersListView.as_view(), name='all_users'),
    path('builtadmin/users/add/', UserCreateView.as_view(), name='add_user'),
    path('builtadmin/users/edit/<int:pk>/', UserEditView.as_view(), name='edit_user'),
    path('builtadmin/users/delete/<int:pk>/', UserDeleteView.as_view(), name='delete_user'),
    
    path('updateuserprofile/', views.update_profile, name='update_profile'),
    
]

bookapp/forms.py
from django import forms
from .models import BookSearch, BorrowedBook, Book, Category
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, View
from django.contrib.auth import update_session_auth_hash
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404



class BookSearchForm(forms.ModelForm):
    name_of_book = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': "form-control", 'placeholder': 'Search Book'
    }))
    class Meta:
        model = BookSearch
        fields = ['name_of_book',]

class CreateUserForm(UserCreationForm):
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Enter Username'
    }))
    email = forms.CharField(max_length=100, widget=forms.EmailInput(attrs={
        'class': 'form-control', 'placeholder': 'Enter Email Address'
    }))
    password1 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'At least eight characters'
    }))
    password2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Confirm Password'
    }))
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class BorrowForm(forms.ModelForm):
    class Meta:
        model = BorrowedBook
        fields = ['return_date']
        widgets = {
            'return_date': forms.DateInput(attrs={'type': 'date'}),
        }

class AdminProfileUpdateForm(UserChangeForm):
    email = forms.EmailField(required=True, label='New Email')
    new_password1 = forms.CharField(label='New Password', widget=forms.PasswordInput, help_text='')
    new_password2 = forms.CharField(label='Confirm New Password', widget=forms.PasswordInput, help_text='')

    class Meta:
        model = User
        fields = ('email',)

    def clean_email(self):
        return self.cleaned_data['email']

    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("The two password fields didn't match.")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if self.cleaned_data['new_password1']:
            user.set_password(self.cleaned_data['new_password1'])
        if commit:
            user.save()
        return user

class BookForm(forms.ModelForm):
    new_category = forms.CharField(max_length=100, required=False, help_text="Or add a new category")

    class Meta:
        model = Book
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.all()
        self.fields['category'].required = False

    def save(self, commit=True):
        instance = super(BookForm, self).save(commit=False)
        if commit:
            instance.save()
            self.save_m2m()
        new_category_name = self.cleaned_data.get('new_category')
        if new_category_name:
            category, created = Category.objects.get_or_create(name=new_category_name)
            instance.category.add(category)
        return instance

class DeleteBookForm(forms.Form):
    pass

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'is_staff', 'is_active']

class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'is_staff', 'is_active']
        
        ################################################
        
class UserProfileUpdateForm(UserChangeForm):
    email = forms.EmailField(required=True, label='Email')
    password1 = forms.CharField(label='New Password', widget=forms.PasswordInput, required=False, help_text='')
    password2 = forms.CharField(label='Confirm New Password', widget=forms.PasswordInput, required=False, help_text='')
    
    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        if self.cleaned_data['password1']:
            user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user
    
    
    
    
    
class AdminProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = AdminProfileUpdateForm
    template_name = 'admin_profile.html'

    def get_object(self):
        # Ensure the user can only update their own profile
        return self.request.user

    def form_valid(self, form):
        # Save the form and update the session auth hash if password was changed
        user = form.save()
        update_session_auth_hash(self.request, user)  # This will update the session hash if the password was changed
        return super().form_valid(form)
    
    
    
    


class UsersListView(ListView):
    model = User
    template_name = 'users_list.html'
    context_object_name = 'users'

class UserCreateView(CreateView):
    model = User
    form_class = UserForm
    template_name = 'user_form.html'
    success_url = reverse_lazy('all_users')

class UserEditView(UpdateView):
    model = User
    form_class = EditUserForm
    template_name = 'user_form.html'
    success_url = reverse_lazy('all_users')

class UserDeleteView(View):
    def get(self, request, pk):
        user = get_object_or_404(User, pk=pk)
        user.delete()
        messages.success(request, 'User has been deleted.')
        return redirect('all_users')

bookapp/templates/add_book.html
{% extends "adminbase.html" %}

{% load static %}

{% block title %}
<title>Add Book - Hayah Online Library</title>
{% endblock %}

{% block cssfile %}
<link rel="stylesheet" href="{% static 'css/AddBooksStyle.css' %}">
{% endblock %}

{% block content %}
<div id="addbook">
    <h1>Add Book</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% comment %} <input type="text" name="new_category" placeholder="New Category Name" id="new_category"> {% endcomment %}
        <button type="submit" class="btn">Add Book</button>
    </form>
</div>
{% endblock %}

bookapp/templates/admin_all_books.html
{% extends "adminbase.html" %}

{% load static %}

{% block title %}
<title>Admin - All Books</title>
{% endblock %}

{% block cssfile %}
<link rel="stylesheet" href="{% static 'css/admin_all_books.css' %}">
{% endblock %}

{% block content %}
<div id="addbook">
    <div class="container">
        <h1>All Books</h1>
        {% comment %} <form class="form-inline my-2 my-lg-0" action="{% url 'admin_search_books' %}" method="get">
            <div class="input-group">
                <input class="form-control mr-sm-2" type="search" placeholder="Search Book" aria-label="Search" name="q">
                <select class="custom-select" name="search_type">
                    <option value="title" selected>Title</option>
                    <option value="author">Author</option>
                    <option value="category">Category</option>
                </select>
                <div class="input-group-append">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </div>
            </div>
        </form> {% endcomment %}
    
        <div class="book-container">
            {% for book in books %}
            <div class="book">
                <img src="{{ book.cover_image.url }}" alt="{{ book.title }}">
                <h2>{{ book.title }}</h2>
                <p>{{ book.author }}</p>
                <p>{{ book.category.all|join:", " }}</p>
                <p>{{ book.price }}</p>
                <a class="btn" href="{% url 'edit_book' book.pk %}">Edit</a>
                <a class="btn" href="{% url 'delete_book' book.pk %}">Delete</a>
            </div>
            {% empty %}
            <p>No books found.</p>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

bookapp/templates/admin_profile.html
{% extends "adminbase.html" %}

{% load static %}

{% block title %}
    <title>Admin Profile - Hayah Online Library</title>
{% endblock %}

{% block cssfile %}
<link rel="stylesheet" href="{% static 'css/AdminProfileStyle.css' %}">
{% endblock %}

{% block content %}
<div id="admin_profile">
    <form method="post">
        <h1>Update Profile</h1>
        {% csrf_token %}
        <div id="form-control">
            <label for="id_email">New Email:</label>
            {{ form.email }}
        </div>
        <div id="form-control">
            <label for="id_new_password1">New Password:</label>
            {{ form.new_password1 }}
        </div>
        <div id="form-control">
            <label for="id_new_password2">Confirm New Password:</label>
            {{ form.new_password2 }}
        </div>
        <button type="submit" class="btn">Update Profile</button>
    </form>
</div>
{% endblock %}

bookapp/templates/admin_search_books.html
{% extends "adminbase.html" %}

{% load static %}

{% block title %}
    <title>Admin search - All Books</title>
{% endblock %}

{% block cssfile %}
<link rel="stylesheet" href="{% static 'css/admin_all_books.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1>Search Books</h1>
    <form class="form-inline my-2 my-lg-0" action="{% url 'admin_search_books' %}" method="get">
        <div class="input-group">
            <input class="form-control mr-sm-2" type="search" placeholder="Search Book" aria-label="Search" name="q">
            <select class="custom-select" name="search_type">
                <option value="title" selected>Title</option>
                <option value="author">Author</option>
                <option value="category">Category</option>
            </select>
            <div class="input-group-append">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </div>
        </div>
    </form>

    {% if searched_books %}
    <ul class="book-list">
        {% for book in searched_books %}
        <li class="book-item">
            <div class="book-details">
                <h2>{{ book.title }}</h2>
                <img src="{{ book.cover_image.url }}" alt="{{ book.title }}">
                <p>{{ book.author }}</p>
                <p>{{ book.category.all|join:", " }}</p>
                <p>{{ book.price }}</p>
                <a class="btn" href="{% url 'edit_book' book.pk %}">Edit</a>
                <a class="btn" href="{% url 'delete_book' book.pk %}">Delete</a>
            </div>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <div>
        <h3>No books found</h3>
    </div>
    {% endif %}
</div>
{% endblock %}

bookapp/templates/book_detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    <title>{{ book.title }} Details - Hayah Online Library</title>
{% endblock %}

{% block cssfile %}
<link rel="stylesheet" href="{% static 'css/book_detail.css' %}">
{% endblock %}

{% block content %}
<div id="bookdetails">
    <div class="book-details">
        <h2>{{ book.title }}</h2>
        <img src="{{ book.cover_image.url }}" alt="{{ book.title }}" id="book-cover">
        <p class="author">Author: {{ book.author }}</p>
        <p class="summary">Summary: {{ book.summary }}</p>
        
         {% if book.availability %}
            <a href="{% url 'borrow_book' book.slug %}" class="btn">Borrow</a>
        {% else %}
            <p class="unavailable-message">This book is currently unavailable for borrowing.</p>
        {% endif %} 
    </div>

    <div class="similar-books">
        <h3>Similar Books</h3>
        <ul class="similar_books">
            {% for similar_book in similar_books %}
                <li>
                    <a href="{% url 'book_detail' similar_book.slug %}">
                        <img src="{{ similar_book.cover_image.url }}" alt="{{ similar_book.title }}" class="book-thumbnail">
                        <p class="book-title">{{ similar_book.title }}</p>
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
    
{% endblock %}

bookapp/templates/borrow_book.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    <title>{{ book.title }} Borrow - Hayah Online Library</title>
{% endblock %}

{% block cssfile %}
<link rel="stylesheet" href="{% static 'css/borrowbook.css' %}">
{% endblock %}

{% block content %}
<div class="borrowbook">
<h2>Borrow {{ book.title }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn">Borrow</button>
</form>
</div>
{% endblock %}

bookapp/templates/category_detail.html
{% extends "base.html" %}

{%block title%}
    <title>categories - Hayah online library</title>
{%endblock%}

{%block content%}

<h1>{{ category }} Books</h1>  
    <div class="book-container">
        {% for book in category.books.all %}
        <div class="book">
            <a href = " {% url 'book_detail' book.slug %}"><img src="{{ book.cover_image.url }}" alt="{{ book.title }}"></a>
            <h2>{{ book.title }}</h2>
            <p>{{ book.author }}</p>
        </div>
        {% endfor %}
    </div> 

{%endblock%}

bookapp/templates/delete_book.html
{% extends "adminbase.html" %}

{% load static %}

{% block title %}
    <title>delete Book - All Books</title>
{% endblock %}

{% block cssfile %}
<link rel="stylesheet" href="{% static 'css/editbook.css' %}">
{% endblock %}

{% block content %}
<p>Are you sure you want to delete {{ book.title }}?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn">Delete</button>
</form>
{% endblock %}

bookapp/templates/edit_book.html
{% extends "adminbase.html" %}

{% load static %}

{% block title %}
    <title>Edit Book - All Books</title>
{% endblock %}

{% block cssfile %}
<link rel="stylesheet" href="{% static 'css/editbook.css' %}">
{% endblock %}

{% block content %}
<div id="editbook">
    <h1>Edit Book</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn" type="submit">Save Changes</button>
    </form>
</div>


{% endblock %}

bookapp/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block title %}
<title>Home - Hayah online library</title>
{% endblock %}

{% block cssfile %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}
<div class="library-container">
    <div class="library-info">
        <h4>Hayah Library provides you</h4>
        <ul>
            <li>Access to a vast collection of books from anywhere at any time.</li>
            <li>Convenience of browsing, borrowing, and returning books online.</li>
            <li>Opportunity for readers to discover new authors and genres easily.</li>
            <li>Ability to avoid physical library constraints such as limited operating hours.</li>
            <li>Eco-friendly option that reduces the need for printed materials.</li>
            <li>Potential for enhanced organization and categorization of books for efficient searching.</li>
            <li>Community features like book reviews, recommendations, and discussions to engage users.</li>
        </ul>        
    </div>
    <div class="block">
        <h2>Reading gives one person more than one life</h2>
    </div>
</div>

<!-- Recommended Books -->
<div class="homebooks">
    <div class="recommended-books">
        <h4 class="booktype">Recommended Books</h4>
        <div class="Tbooks">
            {% for book in recommended_books %}
            <div class="book">
                <a href="{% url 'book_detail' book.slug %}"><img src="{{ book.cover_image.url }}" alt="{{ book.title }}"></a>
            </div>
            {% endfor %}
        </div>
    </div>
    
    <hr>
    
    <!-- Top Fiction Books -->
    <div class="top-fiction-books">
        <h4 class="booktype">Top Fiction Books</h4>
        <div class="Tbooks">
            {% for book in fiction_books %}
            <div class="book">
                <a href="{% url 'book_detail' book.slug %}"><img src="{{ book.cover_image.url }}" alt="{{ book.title }}"></a>
            </div>
            {% endfor %}
        </div>
    </div>
    
    <hr>
    
    <!-- Top Business Books -->
    <div class="top-business-books">
        <h4 class="booktype">Top Business Books</h4>
        <div class="Tbooks">
            {% for book in business_books %}
            <div class="book">
                <a href="{% url 'book_detail' book.slug %}"><img src="{{ book.cover_image.url }}" alt="{{ book.title }}"></a>
            </div>
            {% endfor %}
        </div> 
    </div>

</div>

{% endblock %}

bookapp/templates/login.html
{% extends 'base.html' %}

{% block title %}
    <title>Login - Hayah online library</title>
{% endblock %}

{% load static %}

{% block cssfile %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block content %}
<div id="container" style="height: 400px;">
    <div class="header">
        <h2>Login</h2>
    </div>
    <form action="{% url 'login' %}" method="POST">
        {% csrf_token %}
        <div class="form-control">
            <label>Username:</label>
            <input type="text" name="username" class="form-control" placeholder="Enter Username" maxlength="100" autofocus required id="id_username">
        </div>
        <div class="form-control">
            <label>Password:</label>
            <input type="password" name="password" class="form-control" placeholder="At least eight characters" maxlength="100" required id="id_password">
        </div>
        {% for message in messages %}
        <p class="successMsg">{{ message }}</p>
        {% endfor %}
        <div id="haveAnAccount">
            <p>Don't have an account?</p>
            <a href="{% url 'register' %}" class="register">Register</a>
        </div>
        <button type="submit" class="btn">Login</button>
    </form>
    
</div>
{% endblock %}

bookapp/templates/my_borrowed_books.html
{% extends 'base.html' %}

{% load static %}

{%block title%}
    <title>my_borrowed_books - Hayah online library</title>
{%endblock%}

{% block cssfile %}
<link rel="stylesheet" href="{%static 'css/my_borrowed_books.css' %}">
{% endblock %}




{% block content %}
<div class="myborrowbook">
<h2 id="my_borrowed_books">My Borrowed Books</h2>
<ul>
    {% for borrow in borrowed_books %}
    <li>
        {{ borrow.book.title }} - Due on: {{ borrow.return_date }}
        {% if not borrow.returned %}
        <form method="post" action="{% url 'return_book' borrow.pk %}">
            {% csrf_token %}
            <button type="submit" class="btn">Return</button>
        </form>
        <a href="{{ borrow.book.pdf.url }}" download="{{ borrow.book.title }}.pdf">
            <button id="download">
                Download PDF
                <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                    <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                    <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                </svg>
            </button>
        </a> 
        {% else %}
        <span>Returned</span>
        {% endif %}
    </li>
    {% endfor %}
</ul>
</div>
{% endblock %}

bookapp/templates/register.html
{% extends "base.html" %}
{% block title %}
    <title>Sign Up - Hayah online library</title>
{% endblock %}

{% load static %}

{% block cssfile %}
<link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock %}

{% block content %}
<div id="container">
    <div class="header">
        <h2>Sign Up</h2>
    </div>
    <form action="#" method="POST">
        {% csrf_token %}
        <div class="form-control">
            <label>Username:</label>
            {{ register_form.username }}
        </div>
        <div class="form-control">
            <label>Email:</label>
            {{ register_form.email }}
        </div>
        <div class="form-control">
            <label>Password:</label>
            {{ register_form.password1 }}
        </div>
        <div class="form-control">
            <label>Confirm Password:</label>
            {{ register_form.password2 }}
        </div>
        {{ register_form.errors }}
        <div id="haveAnAccount">
            <p>Already have an account?</p>
            <a href="{% url 'login' %}" class="btnone"><strong>Login</strong></a>
        </div>
        <button type="submit" class="btn">Register</button>
    </form>
</div>
{% endblock %}

bookapp/templates/update_profile.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    <title>User Profile - Hayah Online Library</title>
{% endblock %}

{% block cssfile %}
<link rel="stylesheet" href="{% static 'css/update_profile.css' %}">
{% endblock %}

{% block content %}
<div class="udateuser">
    <h2>Profile</h2>
    <form method="post">
        {% csrf_token %}
        <div id="form-control">
            <label>Email:</label>
            {{ form.email }}
        </div>
        <div id="form-control">
            <label>New Password:</label>
            {{ form.password1 }}
        </div>
        <div id="form-control">
            <label>Confirm New Password:</label>
            {{ form.password2 }}
        </div>
        <button type="submit" class="btn">Update</button>
    </form>
</div>
{% endblock %}